# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('countId', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
