# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compute', '0003_auto_20160913_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='count',
        ),
        migrations.AddField(
            model_name='count',
            name='searchCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='count',
            name='visitCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
