# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compute', '0004_auto_20160913_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='searchCount',
            field=models.IntegerField(default=0),
        ),
    ]
